import cv2
import os
import numpy as np
from services.model_loader import model_loader
from services.face_detection import align_face
from services.database.store import save_face

def get_face_embeddings(image_path: str):
    """
    Reads an image, aligns the face, and returns a stable embedding.
    """
    img = cv2.imread(image_path)
    if img is None:
        return None
    
    faces = model_loader.face_app.get(img)
    if not faces:
        return None
    
    # 1. Detect Face
    face = faces[0]
    
    # 2. Use the embedding already generated by face_app.get()
    # Redundant alignment/recognition call removed to save time
    embedding = face.embedding
    
    # 3. Explicit normalization for stable comparison
    if embedding is not None:
        norm_val = np.linalg.norm(embedding)
        if norm_val > 0:
            embedding = embedding / norm_val
            
    return embedding

def get_multiple_embeddings(image_paths: list):
    """
    Processes multiple images and saves embeddings to database.
    """
    results = []
    for path in image_paths:
        emb = get_face_embeddings(path)
        if emb is not None:
            name = os.path.basename(path)
            milvus_id = save_face(name, emb)
            results.append({"name": name, "id": str(milvus_id)})
    return results

    return results
